// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWZa2Okf4YCzxkVMJ5dpA3vsJ-O2Aqidk',
    appId: '1:169581897180:web:ee77e81012c2295b1a9b19',
    messagingSenderId: '169581897180',
    projectId: 'bed-app-ef8f8',
    authDomain: 'bed-app-ef8f8.firebaseapp.com',
    storageBucket: 'bed-app-ef8f8.firebasestorage.app',
    measurementId: 'G-7GMWKKXPB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuyhAr21DfK0DAjNdYyPoLDHn5GAE6Hok',
    appId: '1:169581897180:android:32ec53345bd411f51a9b19',
    messagingSenderId: '169581897180',
    projectId: 'bed-app-ef8f8',
    storageBucket: 'bed-app-ef8f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEzGgAVAEGeHJPlzncOq-UKzJZOuuOSkQ',
    appId: '1:169581897180:ios:4378f6b819de0e641a9b19',
    messagingSenderId: '169581897180',
    projectId: 'bed-app-ef8f8',
    storageBucket: 'bed-app-ef8f8.firebasestorage.app',
    iosClientId: '169581897180-7qgjh3sfoc95qhm72laduhg752teila6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bedApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEzGgAVAEGeHJPlzncOq-UKzJZOuuOSkQ',
    appId: '1:169581897180:ios:4378f6b819de0e641a9b19',
    messagingSenderId: '169581897180',
    projectId: 'bed-app-ef8f8',
    storageBucket: 'bed-app-ef8f8.firebasestorage.app',
    iosClientId: '169581897180-7qgjh3sfoc95qhm72laduhg752teila6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bedApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWZa2Okf4YCzxkVMJ5dpA3vsJ-O2Aqidk',
    appId: '1:169581897180:web:76c8751dd8f0c81c1a9b19',
    messagingSenderId: '169581897180',
    projectId: 'bed-app-ef8f8',
    authDomain: 'bed-app-ef8f8.firebaseapp.com',
    storageBucket: 'bed-app-ef8f8.firebasestorage.app',
    measurementId: 'G-6BSQNWB6S6',
  );

}